CREATE TABLE mentors (
    id INTEGER PRIMARY KEY,
    email TEXT,
    password TEXT,
    first_name TEXT,
    surname TEXT,
    age INTEGER,
    gender TEXT,
    contact_number INTEGER,
    profile_job_title TEXT,
    profile_job_information TEXT,
    profile_interests TEXT,
    profile_text TEXT,
    linked_mentee_id INTEGER,
    current_requests_id INTEGER,
);